# Generated by Django 5.1.3 on 2024-12-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userscript_delete_challengequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscript',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userscript',
            name='mana',
            field=models.IntegerField(default=100),
        ),
    ]
