# Generated by Django 5.1.3 on 2024-12-26 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userscript_hp_userscript_mana'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscript',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscript',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
