# Generated by Django 5.1.3 on 2025-01-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0006_alter_action_cast_time_alter_action_cooldown'),
        ('users', '0005_userscript_created_at_userscript_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscript',
            name='actions',
            field=models.ManyToManyField(blank=True, to='script.action'),
        ),
    ]
