# Generated by Django 6.0.5 on 2026-05-21 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userscript_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_cast_cancel', models.BooleanField(default=False, help_text='When enabled, clicking a new heal target while casting shows an Abort button instead of immediately cancelling. Useful if you want to avoid accidental interruptions.', verbose_name='Confirm before cancelling a cast')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
