# Generated by Django 6.0.5 on 2026-05-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='confirm_cast_cancel',
            field=models.BooleanField(default=True, help_text='When enabled, clicking a new heal target while casting shows an Abort button instead of immediately cancelling. Useful if you want to avoid accidental interruptions.', verbose_name='Confirm before cancelling a cast'),
        ),
    ]
