# Generated by Django 6.0.5 on 2026-05-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0008_rename_health_npcscript_hp_rename_health_script_hp'),
        ('users', '0008_alter_userpreferences_confirm_cast_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscript',
            name='party_slot',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Party position 1–5, or null if on bench. Slots 1–3=melee, 4–5=ranged.', null=True),
        ),
        migrations.AddConstraint(
            model_name='userscript',
            constraint=models.UniqueConstraint(condition=models.Q(('party_slot__isnull', False)), fields=('user', 'party_slot'), name='unique_party_slot_per_user'),
        ),
    ]
