# Generated by Django 6.0.5 on 2026-05-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('script', '0008_rename_health_npcscript_hp_rename_health_script_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display/unlock order')),
                ('is_demo', models.BooleanField(default=False, help_text='Demo stages are accessible without an account')),
                ('enemy_count', models.PositiveIntegerField(default=3, help_text='How many enemies to pick from the pool')),
                ('demo_party_size', models.PositiveIntegerField(default=3, help_text='How many scripts to pick from demo_party_pool')),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('min_party_level', models.PositiveIntegerField(default=1, help_text='Minimum average party level required to unlock this stage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demo_party_pool', models.ManyToManyField(blank=True, help_text='Scripts randomly assigned to anon players in demo mode', related_name='demo_stages', to='script.script')),
                ('enemy_pool', models.ManyToManyField(help_text='Pool of enemies to randomly draw from', to='script.npcscript')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
