# Generated by Django 6.0.5 on 2026-05-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='demo_party_size',
        ),
        migrations.AddField(
            model_name='stage',
            name='party_size',
            field=models.PositiveIntegerField(default=5, help_text='Number of party members allowed in this stage (excluding Efilwol)'),
        ),
    ]
