# Generated by Django 5.1.3 on 2024-12-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('role', models.CharField(choices=[('tank', 'Tank'), ('healer', 'Healer'), ('dps', 'DPS')], max_length=10)),
                ('damage_range', models.CharField(choices=[('melee', 'Melee'), ('ranged', 'Ranged')], max_length=10)),
                ('damage_specialization', models.CharField(choices=[('physical', 'Physical'), ('lightning', 'Lightning'), ('fire', 'Fire'), ('ice', 'Ice'), ('earth', 'Earth'), ('water', 'Water'), ('poison', 'Poison'), ('necrotic', 'Necrotic'), ('none', 'None')], max_length=20)),
                ('subclass', models.CharField(max_length=30)),
                ('min_health', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('damage', models.IntegerField()),
                ('mana_cost', models.IntegerField()),
                ('cooldown', models.IntegerField()),
                ('damage_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
