# Generated by Django 5.1.3 on 2024-12-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='max_health',
            new_name='health',
        ),
        migrations.RemoveField(
            model_name='script',
            name='min_health',
        ),
        migrations.RemoveField(
            model_name='script',
            name='subclass',
        ),
    ]
