# Generated by Django 5.1.3 on 2024-12-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_rename_max_health_script_health_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spells',
            new_name='Spell',
        ),
        migrations.AlterField(
            model_name='script',
            name='role',
            field=models.CharField(choices=[('tank', 'Tank'), ('dps', 'DPS')], max_length=10),
        ),
    ]
