# Generated by Django 5.1.3 on 2024-12-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0003_rename_spells_spell_alter_script_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='damage_type',
        ),
        migrations.AddField(
            model_name='spell',
            name='attribute_modified',
            field=models.CharField(blank=True, choices=[('health', 'Health'), ('mana', 'Mana')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration of the spell in seconds.  For damage or healing this will be the hot/dot time', null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='modifier',
            field=models.IntegerField(default=0, help_text='Numerical scaling factor for this spell e.g. the damage or healing done. But can also be the strength of a buff'),
        ),
        migrations.AddField(
            model_name='spell',
            name='scope',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple'), ('party', 'Party')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='spell',
            name='type',
            field=models.CharField(choices=[('physical', 'Physical'), ('lightning', 'Lightning'), ('fire', 'Fire'), ('ice', 'Ice'), ('earth', 'Earth'), ('water', 'Water'), ('poison', 'Poison'), ('necrotic', 'Necrotic'), ('healing', 'Healing'), ('buff', 'Buff'), ('debuff', 'Debuff')], default='physical', max_length=20),
        ),
    ]
