# Generated by Django 5.1.3 on 2025-01-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0004_remove_spell_damage_remove_spell_damage_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('base_power', models.IntegerField(default=0, help_text='Numerical scaling factor for this spell e.g. the damage or healing done. But can also be the strength of a buff')),
                ('type', models.CharField(choices=[('physical', 'Physical'), ('lightning', 'Lightning'), ('fire', 'Fire'), ('ice', 'Ice'), ('earth', 'Earth'), ('water', 'Water'), ('poison', 'Poison'), ('necrotic', 'Necrotic'), ('holy', 'Holy'), ('dark', 'Dark'), ('healing', 'Healing'), ('buff', 'Buff'), ('debuff', 'Debuff')], default='physical', max_length=20)),
                ('cast_time', models.IntegerField(blank=True, help_text='Time in seconds to cast the spell.  For damage or healing this will be the cast time', null=True)),
                ('cooldown', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, help_text='Duration of the spell in seconds.  For damage or healing this will be the hot/dot time', null=True)),
                ('max_targets', models.IntegerField(default=1)),
                ('attribute_modified', models.CharField(blank=True, choices=[('health', 'Health'), ('mana', 'Mana')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NPCScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('damage_specialization', models.CharField(choices=[('physical', 'Physical'), ('lightning', 'Lightning'), ('fire', 'Fire'), ('ice', 'Ice'), ('earth', 'Earth'), ('water', 'Water'), ('poison', 'Poison'), ('necrotic', 'Necrotic'), ('holy', 'Holy'), ('dark', 'Dark'), ('none', 'None')], max_length=20)),
                ('health', models.IntegerField()),
                ('defence', models.DecimalField(decimal_places=1, max_digits=3)),
                ('resistance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('attack', models.DecimalField(decimal_places=1, max_digits=3)),
                ('speed', models.DecimalField(decimal_places=1, max_digits=3)),
                ('luck', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
        migrations.AddField(
            model_name='script',
            name='attack',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='defence',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='luck',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='resistance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='speed',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='script',
            name='damage_specialization',
            field=models.CharField(choices=[('physical', 'Physical'), ('lightning', 'Lightning'), ('fire', 'Fire'), ('ice', 'Ice'), ('earth', 'Earth'), ('water', 'Water'), ('poison', 'Poison'), ('necrotic', 'Necrotic'), ('holy', 'Holy'), ('dark', 'Dark'), ('none', 'None')], max_length=20),
        ),
    ]
