# Generated by Django 5.1.3 on 2025-01-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0005_action_npcscript_delete_spell_script_attack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='cast_time',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Time in seconds to cast the spell.  For damage or healing this will be the cast time', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='cooldown',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
