# Generated by Django 5.1.3 on 2025-01-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0006_alter_action_cast_time_alter_action_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcscript',
            name='action_pool',
            field=models.ManyToManyField(to='script.action'),
        ),
        migrations.AddField(
            model_name='script',
            name='action_pool',
            field=models.ManyToManyField(to='script.action'),
        ),
    ]
