# Generated by Django 5.1.3 on 2025-01-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0007_npcscript_action_pool_script_action_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npcscript',
            old_name='health',
            new_name='hp',
        ),
        migrations.RenameField(
            model_name='script',
            old_name='health',
            new_name='hp',
        ),
    ]
